# Generated by Django 4.1.7 on 2023-02-28 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('acitvity', models.TextField(blank=True, null=True)),
                ('Temperature', models.TextField(blank=True, null=True)),
                ('Altitude', models.TextField(blank=True, null=True)),
                ('mentalstate', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('username', models.EmailField(blank=True, max_length=254, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('First_Name', models.TextField(blank=True, null=True)),
                ('Last_Name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('age', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('First_Name', models.TextField(blank=True, null=True)),
                ('Last_Name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
