# Generated by Django 4.1.7 on 2023-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='username',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
