# Generated by Django 4.1.7 on 2023-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
