# Generated by Django 4.1.7 on 2023-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
