# Generated by Django 4.1.7 on 2023-03-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
