# Generated by Django 4.1.7 on 2023-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('products', models.CharField(max_length=255)),
            ],
        ),
    ]
