# Generated by Django 4.1.7 on 2023-03-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoPremium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
