# Generated by Django 4.1.7 on 2023-03-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DirectMessaging', '0006_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
    ]
