# Generated by Django 4.1.7 on 2023-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DirectMessaging', '0007_rename_sender_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
